spring.application.name=ScreenSoundMusicas
spring.datasource.url=jdbc:postgresql://localhost:5432/musicas_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
langchain4j.google-ai-gemini.chat-model.api-key=${API_KEY_GEMINI}
langchain4j.google-ai-gemini.chat-model.model-name=gemini-1.5-flash